output: output
input: output/csv

blob:
  BATCH_SIZE: 10
  container_name: "demothoncontainerplain"


simulation:
  processes:
    p1:
      script: p1.py
      latency: 1
    p2:
      script: p2.py
      latency: 2
    p3:
      script: p3.py
      latency: 1.5
    p4:
      script: p4.py
      latency: 0.5

telemetry-service:
  interval: 5

  sensors:
    sen1:
      min: 0
      max: 100
      threshold: 50
    sen2:
      min: 0
      max: 100
      threshold: 50
    sen3:
      min: 0
      max: 100
      threshold: 50
    sen4:
      min: 0
      max: 100
      threshold: 50
    sen5:
      min: 0
      max: 100
      threshold: 50
    sen6:
      min: 0
      max: 100
      threshold: 50
